version: '3.8'

services:
    producer:
        image: golang-rabbitmq-example-producer
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile.producer
        environment:
            - RABBITMQ_ADDR=rabbitmq:5672
        depends_on:
            - rabbitmq
    consumer-1:
        image: golang-rabbitmq-example-consumer
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile.consumer
        environment:
            - RABBITMQ_ADDR=rabbitmq:5672
        depends_on:
            - rabbitmq
    consumer-2:
        image: golang-rabbitmq-example-consumer
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile.consumer
        environment:
            - RABBITMQ_ADDR=rabbitmq:5672
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
