FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY producer/producer.go ./
RUN CGO_ENABLED=0 go build -o producer

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/producer /app/producer
RUN ls -la /app  # List the contents of /app in the final stage
CMD ["/app/producer"]
