FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY consumer/consumer.go ./
RUN CGO_ENABLED=0 go build -o consumer

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/consumer /app/consumer
CMD ["/app/consumer"]
